name: Manual Trigger

on: [ workflow_dispatch ]

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          pip install urllib3
          pip install beautifulsoup4
          pip install requests
          pip install selenium==3.13.0
          pip install lxml
          pip install google_auth_oauthlib
          pip install google-api-python-client
          pip install google-auth-httplib2
          pip install get_chrome_driver
          
          
      - name: Run script
        run: |
          python main.py
        env:
          KEIO_ID: ${{ secrets.KEIO_ID }}
          KEIO_PASS: ${{ secrets.KEIO_PASS }}
          TELL: ${{ secrets.TELL }}
          NOTIFY_TOKEN: ${{ secrets.NOTIFY_TOKEN }}
          TWIN_TOKEN: ${{ secrets.TWIN_TOKEN }}
