name: Manual Trigger

on: [ workflow_dispatch ]

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          pip install urllib3
          pip install beautifulsoup4
          pip install requests
          pip install selenium
          pip install futures
          pip install lxml
          pip install google_auth_oauthlib
          pip install google-api-python-client
          pip install google-auth-httplib2
          pip install get-chrome-driver --upgrade
          
      - name: Install Chrome
        run: |
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt update
          sudo apt-get install google-chrome-stable
          
      - name: Run script
        run: |
          # 定期実行するファイルを指定。・・・③
          python reserve.py
